### ISSUE TITLE
crt-interlaced-halation GLSL

### ISSUE THREAD

**Issue by SixWingedFreak** [libretro/common-shaders#102]
In RetroArch 1.4.1 x64, the GLSL version of crt-interlaced-halation is missing pass2, it's being called for in the glslp file

**Comment by hizzlekizzle** [comment]
Yeah, that means the conversion script couldn't handle it for whatever reason. I've manually converted it now, though, so once it makes its way into the online updater, it should be usable.

**Comment by hizzlekizzle** [comment]
@SixWingedFreak 
This should be resolved now, so I'm closing the issue. If not, feel free to reopen it.
