### ISSUE TITLE
Port a few SimoneT shaders

### ISSUE THREAD

**Issue by wingedonezero** [libretro/common-shaders#105]
Mostly i was thinking his new Simple Edge Directed Interpolation, manga shader and his pure 2d and 2d 3d shader. ive attached them below if its even possible to convert them.

[Simple Edge Directed Interpolation (SEDI) v1.0.zip](https://github.com/libretro/common-shaders/files/904830/Simple.Edge.Directed.Interpolation.SEDI.v1.0.zip)
[SimoneT pure 2D games Shader v 1.16 WIP.zip](https://github.com/libretro/common-shaders/files/904831/SimoneT.pure.2D.games.Shader.v.1.16.WIP.zip)
[SimoneT mixed 3D - 2D games Shader v 1.16 WIP.zip](https://github.com/libretro/common-shaders/files/904829/SimoneT.mixed.3D.-.2D.games.Shader.v.1.16.WIP.zip)
[Manga shader v 1.0.zip](https://github.com/libretro/common-shaders/files/904828/Manga.shader.v.1.0.zip)

**Comment by hizzlekizzle** [comment]
can you get some screenshots of any of those?

**Comment by wingedonezero** [comment]
Here are some screenshots all are at 1080p youll have to click on the pictures to see detail gains.
No Shader 2d
![2d noshader](https://cloud.githubusercontent.com/assets/15163316/24820040/1dacfc98-1bb5-11e7-83e5-7826c3262819.png)

SimoneT pure 2D games Shader v 1.16 WIP
![simonet pure 2d games shader v 1 16 wip](https://cloud.githubusercontent.com/assets/15163316/24820068/3e685176-1bb5-11e7-9655-c0113bbf5986.png)

Sedi 2d
![sedi 2d](https://cloud.githubusercontent.com/assets/15163316/24820141/8b22f156-1bb5-11e7-91f4-7579e84832f7.png)

Manga 2d
![manga 2d](https://cloud.githubusercontent.com/assets/15163316/24820202/dd1de9ac-1bb5-11e7-98d2-d346ea71a7e7.png)

3d Noshader
![3d no shader](https://cloud.githubusercontent.com/assets/15163316/24820219/f6cffde0-1bb5-11e7-8e29-312f96a18f88.png)

SimoneT mixed 3D - 2D games
![simonet mixed 3d - 2d games](https://cloud.githubusercontent.com/assets/15163316/24820234/06288924-1bb6-11e7-9440-ccb579688ad4.png)

Sedi 3d
![sedi](https://cloud.githubusercontent.com/assets/15163316/24820259/22cdb1b2-1bb6-11e7-9594-d2d248ec88dc.png)

**Comment by hizzlekizzle** [comment]
I ported SEDI and the 3d/2d mixed shader to our GLSL format, so you can try them from there. I'm not sure if I got the mixed shader working quite right, though. I'm not sure how the resolution stuff is supposed to work, since pete's OGL2 and RetroArch handle scaling differently.
