### ISSUE TITLE
4x internal and up = lag

### ISSUE THREAD

**Issue by Mickevincent** [libretro/common-shaders#106]
Hello,
I just have a question about mednafen in retroarch. I try to run games in 4 times internal but it causes lag no matter what I do. I have tried with threaded video on and it makes it better, but not enough. (I also have to turn that off in the config before restarting retroarch, because otherwise it crashes.)
It wont let me chose hardware rendering as a video option, only software. I dont know if that would fix it anyway.
My cpu is a i7 4790k and gpu a gtx 980ti and no other game is causing trouble, so it has nothing to do with drivers I suppose. I have also tried different versions on retroarch without succes. 
I also emulated ps1 in 1999 on my Pentium 2 without much trouble so this does not make any sense. What am I doing wrong?

**Comment by TheOligopolist** [comment]
Are you using the PSX HW core? The PSX core runs in software and scaling the resolution is going to result in a very large performance hit.
The PSX HW core is not as accurate but you should be able to bump up the resolution with no significant performance impact.

**Comment by hizzlekizzle** [comment]
This isn't really the right repo for that question, but I'll answer it anyway :)

If you're using the non-HW core, the resolution increases are happening in software, which taxes the CPU exponentially for each increase (it's software rendering). With the *-HW core, it should handle resolution increases with your GPU via either OpenGL or Vulkan, depending on the video driver you've selected in settings > driver and the core option.

FAKEDIT: ninja'ed :)

**Comment by Mickevincent** [comment]
Thanx guys. But it doesnt do any difference and still says "software" as renderer. I cannot change it to hardware.

**Comment by hizzlekizzle** [comment]
Make sure you load the beetle-psx-hw core.

Threaded video isn't typically something you would want. I wouldn't worry about it if I were you.

In your retroarch.cfg, there are settings for video_fullscreen_x/y. If you set those to the 4K resolution (that is, 3840 and 2160, respectively), RetroArch will try to set the mode to 4K when you enter exclusive fullscreen (that is, make sure 'windowed fullscreen' isn't enabled).

**Comment by Mickevincent** [comment]
I do load the hw - core, but it wont work. Maybe I would not need threaded video if it would work with hardware mode, but as it wont work.. well then I kinda have to use the threaded video mode.
I will check out that in the config. Thanx for your help.
