### ISSUE TITLE
handheld/lcd_cgwg simple case sensitivity problem

### ISSUE THREAD

**Issue by MattiHameister** [libretro/common-shaders#12]
In lcd-cgwg.cgp the motion blur file is referenced by 

shader0 = Motionblur-simple.cg

but the file itself is named 

motionblur-simple.cg

Notice the case of the letter "M". To this shaders fails to load on case sensitive filesystems (like mine here). Simply rename this file (or the reference) fixes the problem.

**Comment by hizzlekizzle** [comment]
This was fixed a long time ago but the issue was never closed out. Doing that now.
