### ISSUE TITLE
incorrect path (r57shell royale preset)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/common-shaders#146]
https://github.com/libretro/common-shaders/commit/8cd385246313e10482addd0da9936b7b6fa51608

crt-royale-pal-r57shell.cgp preset don't work:
\shaders_cg\pal\crt-royale-pal-r57shell.cgp = incorrect path (current)
\shaders_cg\crt\crt-royale-pal-r57shell.cgp = correct path 

Default shaders and presets paths (recommended by r57shell) are:
\shaders_cg\crt\crt-royale-pal-r57shell.cgp
\shaders_cg\pal\pal-r57shell.cgp
\shaders_cg\pal\shaders\pal-r57shell.cg
\shaders_cg\pal\resources\nes_lut.png

**Comment by hizzlekizzle** [comment]
should be fixed now.
