### ISSUE TITLE
[Request] GBA Ultrawide Edit

### ISSUE THREAD

**Issue by jiiprah** [libretro/common-shaders#148]
Would anyone be interested in this addition? I edited the GBA gamepad overlay for ultrawide screens (specifically the LG G7 screen).  It's full resolution right now so i would need to compress the image a bit and the buttons aren't animated with presses.
![6rink6d2f9f76kft4qcmbmltej8mtpemsuc5ah3zl0q](https://user-images.githubusercontent.com/41028351/42481698-d0680f70-83b1-11e8-92b2-2c562a8ec5c7.png)

**Comment by hizzlekizzle** [comment]
That looks pretty nice to me. This should go over in the common-overlays repo, though. Would you mind opening this issue over there instead?
