### ISSUE TITLE
run away pixels in all auto-box shaders

### ISSUE THREAD

**Issue by ab235g** [libretro/common-shaders#149]
when I use auto-box shaders on my vertical 16:9 monitor the top and right edges pixels streak across the screen where there should be a black boarder.
![horizontal_runaway](https://user-images.githubusercontent.com/11493921/44620048-afcd0100-a853-11e8-83bf-e87e91df4b8a.jpg)
![vertical_runaway](https://user-images.githubusercontent.com/11493921/44620049-b491b500-a853-11e8-8558-bf19ed24b847.jpg)

**Comment by hizzlekizzle** [comment]
Looks like a clamping issue. Do you get the same result with the glsl or slang versions?

**Comment by ab235g** [comment]
I am currently using the glsl version. I was not aware that I could use other versions with my raspberry pi 3 b+.

**Comment by hizzlekizzle** [comment]
This repo has the Cg/HLSL versions, so that's what I assumed you were using, but that's fine. Since you're using RPi, I know exactly what the problem is. I'll push some fixes up soon.
