### ISSUE TITLE
[Q] Any shader to darken only an area of the screen?

### ISSUE THREAD

**Issue by eadmaster** [libretro/common-shaders#162]
I know the image-adjustment shader can do that on the whole screen, but i am looking for a way to darken only a portion of the screen, like shown in this shot:
![Super Aleste (Japan) (BS)](https://user-images.githubusercontent.com/925171/109658473-e98acb00-7b66-11eb-8bb9-eb86987b3a6d.png)

I'd like to use this with cores supporting widescreen hacks.

**Comment by hizzlekizzle** [comment]
You could use the imgborder shader with a semi-transparent png.

**Comment by eadmaster** [comment]
> You could use the imgborder shader with a semi-transparent png.

thank you for the tip, but that shader seems to scale the image changing the aspect ratio, while i'd like to get an overlay-like effect.

**Comment by HeuristicPerson** [comment]
You can create your own overlay with a semi-transparent .png file. Actually, I think you can put 100% black opaque side bars and then play with the opacity of the overlay in the configuration file.

**Comment by eadmaster** [comment]
thank you, i was able to easily get the desired effect by modyifing the [checker overlay](https://github.com/libretro/common-overlays/blob/master/effects/patterns/checker.cfg). I guess this is faster to render than a shader, so i'll use to this...

**Comment by hizzlekizzle** [comment]
After thinking about this for a while, I did make a shader for it:
![image](https://user-images.githubusercontent.com/2805586/110415974-844c4380-8058-11eb-9a3c-10bc15c80a75.png)
https://pastebin.com/EQhFkAir (slang format only currently)
