### ISSUE TITLE
Borders shaders: custom CRT?

### ISSUE THREAD

**Issue by nikkoman** [libretro/common-shaders#40]
Could you please make my "personally adjusted" cg CRT shader compatible with the cgp border script?

I know nothing about coding and it appears that it's the only way to have borders in the OpenEmu fork.

I have been spending hours adding parts to my file in order to do so but I'm helpless.

This is my shader:
https://dl.dropboxusercontent.com/u/46466649/CRT-tweaked.cg

Thanks in advance.

**Comment by hizzlekizzle** [comment]
guess this done /shrug
