### ISSUE TITLE
About [tex2dblurNxNshared] function in [blur-functions.h]

### ISSUE THREAD

**Issue by kingeric1992** [libretro/common-shaders#72]
Accroding the reference document, and ddx, ddy gradient,
if using tex2Dblur12x12shared as example, with the quad layout (mirrored offset)

>     8a 7a 6a 6b 7b 8b
>     5a 4a 3a 3b 4b 5b
>     2a 1a 0a 0b 1b 2b
>     2c 1c 0c 0d 1d 2d
>     5c 4c 3c 3d 4d 5d
>     8c 7c 6c 6d 7d 8d

the quad vector for gathering should be
```
    quad_gather(quad_vector * sample1_texel_offset * pow(2, 1-tex_uv.w), sample1curr, sample1adjx, sample1adjy, sample1diag);
    quad_gather(quad_vector * sample2_texel_offset * pow(2, 1-tex_uv.w), sample2curr, sample2adjx, sample2adjy, sample2diag);
   ...and so on
```
otherwise the weighting and estimated sample doesn't match up.

**Comment by hizzlekizzle** [comment]
If you want to make a PR to fix it (preferably with a couple of screenshots to compare before/after), I'll merge it.

**Comment by kingeric1992** [comment]
Scrap it, I misunderstood the meaning...

**Comment by hizzlekizzle** [comment]
k, no worries!
