### ISSUE TITLE
Interlacing shader looks wrong on Full screen games

### ISSUE THREAD

**Issue by mckimiaklopa** [libretro/common-shaders#78]
Games with top and bottom bars look fine with the interlacing shader

![ff771411](https://cloud.githubusercontent.com/assets/5818289/16548129/6ab728e8-41b7-11e6-84c7-b029bc4af552.jpg)

Whereas games that are full screen (which accounts for most games) look wrong with the interlacing shader. The distribution of lines look wrong
![retroarch-0704-071539](https://cloud.githubusercontent.com/assets/5818289/16548135/ad10c8e8-41b7-11e6-957f-7abfc3026034.jpg)

**Comment by hizzlekizzle** [comment]
Yeah, that shader is very sensitive to non-integer scaling. You're better off using scanline.glsl or ntsc-gauss-pass.glsl, both of which will be more forgiving.
