### ISSUE TITLE
[Request] Opacity for imgborder.cgp

### ISSUE THREAD

**Issue by shinra358** [libretro/common-shaders#90]
I would like to request an opacity option for the images used for the imgborder.cgp.
Thanks.

**Comment by hizzlekizzle** [comment]
How would that work? You want the border to be able to cover the game screen but with the screen visible behind it?

**Comment by shinra358** [comment]
It would be for unconventional uses like, normal overlays such as watermarks on gameplay vids to save on reencoding time. Or custom overlays like mame and snes9x can use. One of which could be loading a scanline png and the opacity can lighten the effect so it wouldnt appear too dark. Things like that.

**Comment by hizzlekizzle** [comment]
Oh, I see. Well, in that case, is there a reason you want to use a shader instead of an overlay?

**Comment by shinra358** [comment]
Using this on a few other emus other than retroarch. For retroarch, it already has all that built in. When I asked about using overlays in the snes9x github as a new feature, the author recommended me to use the shader stated in the initial post. And that is what brought me here. Because not all emus have overlay support.

**Comment by hizzlekizzle** [comment]
Ah, ok then. Yeah, sure, I can add it. I'll post back here when it's done.

**Comment by shinra358** [comment]
Thx bud, much appreciated.

**Comment by hizzlekizzle** [comment]
Ok, you should be all set:
https://github.com/libretro/common-shaders/commit/296c17638ecc314939080584c9cbb7d624e7468d
Feel free to reopen this if it doesn't act like you expect, etc.

**Comment by shinra358** [comment]
works perfect. all is well ;)

**Comment by shinra358** [comment]
Thx bud. Appreciate it.
