### ISSUE TITLE
[Request] SimonT's NTSC TV Color Emulation

### ISSUE THREAD

**Issue by nuanug** [libretro/common-shaders#91]
please port SimoneT's NTSC TV Color Emulation PeteOpenGL2 shader to GLSL. i put the original post below
[Original Post](http://ngemu.com/threads/links-and-guides-to-custom-shaders-for-petes-opengl2-plugin.76098/page-37#post-2485969)
and the latest version of his shader
[Latest Version](http://ngemu.com/threads/links-and-guides-to-custom-shaders-for-petes-opengl2-plugin.76098/page-38#post-2487761)
Sample Images
[Sample](http://imgur.com/a/TNZr9)

**Comment by hizzlekizzle** [comment]
I just added it to the slang/vulkan shaders. I can make a Cg version soon (probably tomorrow) and it will get auto-converted to GLSL.

**Comment by nuanug** [comment]
thank you very much.

**Comment by hizzlekizzle** [comment]
Alright, Cg version is in, autoconverted GLSL version should be available in the online updater within a day or so.

**Comment by nuanug** [comment]
thank you hizzlekizzle.
