### ISSUE TITLE
[Request] Magnify/Overscan Shader 

### ISSUE THREAD

**Issue by shinra358** [libretro/common-shaders#94]
In Reshade there is a shader called Magnify which can stretch each side of the screen individually in order to remove bars, glitches, etc on the edges of the screen. I would like for this to be ported or created for the common shaders. Using it from Reshade results in scanlines being messed up because of Reshade manipulating the entire screen. But if it were a shader, I wouldn't have to worry about the scanlines being messed up. This is needed for things like the nes cores. Where they have top/bottom and left/right grouped together. Some games might need one side tinkered with. Like the nes, usually needs just the left and the top tinkered with. The current overscan option for nes takes away too much from the bottom as it overscans the top. The reshade shader can take away from the top while still keeping the bottom intact. So if someone can create this, that would be great.

**Comment by hizzlekizzle** [comment]
Already handling this on the forum.
