### ISSUE TITLE
tvout-tweaks.glsl is missing options

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/common-shaders#95]
TVOUT_RESOLUTION, TVOUT_COMPOSITE_CONNECTION, TVOUT_TV_COLOR_LEVELS options seem to be missing from the build on the buildbot.

**Comment by GeneralFailer** [comment]
Also snes-hires-blend.glsl is completely missing.

**Comment by hizzlekizzle** [comment]
I hand-ported tvout-tweaks last night, so it should be available via the updater soon with parameters intact. I'll try to port snes-hires-blend at some point.

**Comment by GeneralFailer** [comment]
Yeah, thanks, I've actually already tried it.
